[app]

# Titulo do aplicatio
title = Cade meu Onibus

# Nome do pacote
package.name = cademeuonibus

# Dominio do pacote
package.domain = org.cademeuonibus

# Diretorio fonte
source.dir = .

# Extensoes de arquivo a incluir
source.include_exts = py,html,png,jpg,json

# Versao do app
version = 1.0.0

# Requisitos Python
requirements = python3,kivy,requests,urllib3,charset-normalizer,idna,certifi,android,pyjnius

# Permissoes Android
android.permissions = INTERNET,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,ACCESS_NETWORK_STATE

# Orientacao
orientation = portrait

# Tela cheia
fullscreen = 0

# API minima (Android 9 = API 28)
android.minapi = 28

# API alvo (Android 14 = API 34)
android.api = 34

# NDK
android.ndk = 25b

# Arquiteturas
android.archs = arm64-v8a,armeabi-v7a

# Aceitar licenca SDK
android.accept_sdk_license = True

# Tema Android
android.theme = @android:style/Theme.Material.Light.NoActionBar

# AndroidX
android.enable_androidx = True

# Gradle dependencies
android.gradle_dependencies = androidx.webkit:webkit:1.6.1

# Logcat
android.logcat_filters = *:S python:D
